version: "3.8"
services:
  device-manager-service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      device-manager-db:
        condition: service_healthy

  device-manager-db:
    image: "mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: device_manager_db
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
